name: pax_player
description: A Flutter package for POS (Point of Sale) devices, providing essential methods
  for card reading, barcode scanning, QR code scanning, and more.
Important: THIS PACKAGE WILL WORK ONLY IN ANDROID!
version: 0.0.8
homepage: https://github.com/Mahmoudmv91/pax_player
environment:
  sdk: ">=3.0.6 <4.0.0"
  flutter: ">=3.3.0"
dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
flutter:
  plugin:
    platforms:
      android:
        package: pax.plugin.pki.parhamkish.vakili.pax_player
        pluginClass: PaxPlayerPlugin